### ISSUE TITLE
Add support for custom forms

### ISSUE THREAD

**Issue by boakley** [faxad/ActivFlow#4]
As a developer trying to build a workflow system for my organization, I need to be able to customize the forms presented to the user. For example, a simple workflow might involve editing some HTML with a rich text editor in one activity, and then to be able to preview the rendered data on a review activity page.

I would like the ability to customize the forms presented to the user, while still being able to use the underlying engine to control the flow of activities.

**Comment by boakley** [comment]
This looks really useful, and I appreciate the quick turnaround! However, it's not exactly what this feature request was asking for.  We have other types of widgets that we use for input and output as well. This request wasn't for a wysiwyg editor, it was for a way to customize views in a general purpose way. Adding a wysiwyg edtior was just one of many use cases.

**Comment by faxad** [comment]
Noted.

I'll definitely look into it.

**Comment by boakley** [comment]
I got my terminology mixed up, so I edited the title to hopefully be more accurate (I replaced "view" with 'form"). In short, I need to be able to customize the forms presented by activflow.
