### ISSUE TITLE
Add activity names to task summary

### ISSUE THREAD

**Issue by boakley** [faxad/ActivFlow#5]
At first glance, the UI of activflow is really nice. However, something I'm struggling with is how to visualize what step the workflow is in. For example, when I click on "view tasks" I see task IDs and the status, but no indication of what the next task or activity is. 

For example, a simple workflow might be to create a paragraph of text. Maybe it's an ad for a newspaper, or a description of a product for a website. The flow might be something like edit -> proofread -> review layout -> approve -> move to production. All I see in the summary is "5 Not Started  Reviewer". I have no way of knowing which task it's stuck in.

What I'd like to see instead is a column that shows the task name (eg: "Proofread" or "Layout Review") in addition to the other information. This should be a human-friendly name, so there needs to be a way to attach a name to an activity

**Comment by faxad** [comment]
Excellent point noted. I'm on it.
