### ISSUE TITLE
Error on_delete

### ISSUE THREAD

**Issue by simona2017** [faxad/ActivFlow#9]
Hi, 

I've installed the script and I'm having the following error. Please let me know how I can fix it. Thanks, 
<img width="987" alt="screen shot 2018-06-07 at 7 17 27 pm" src="https://user-images.githubusercontent.com/22427968/41131060-94d92612-6a87-11e8-8855-a3e1b4fab184.png">

**Comment by Harshitg** [comment]
How did you get around this error?

**Comment by adavie1** [comment]
> How did you get around this error?

I would also like to know as well.
